### ISSUE TITLE
How will you use the gdrive repo from another location?

### ISSUE THREAD

**Issue by ibnishak** [Lykos153/git-annex-remote-googledrive#12]
Sorry, newbie question.

I followed your instructions and set up a repo in gdrive. I can push my data to it, which is stored as encrypted. I have a question.

Is it possible to use this folder in gdrive from another machine via git-annex interface? ie, without syncing gdrive to the machine otherwise?

**Comment by Lykos153** [comment]
You can use the remote from different machines. On the second machine you'll need a clone of the repository. Inside the repo, run `git-annex-remote-googledrive setup` again to authenticate with Google. Then just run `git annex enableremote <remote_name>` and you can access the remote.

Note that the special remote only contains the raw (encrypted) data. So after uploading files from machine A to Google you'll need to perform `git annex sync`, so machine B knows where to find them.
