### ISSUE TITLE
cut a release?

### ISSUE THREAD

**Issue by notestaff** [Lykos153/git-annex-remote-googledrive#41]
Maybe, cut a named release 0.11.5rc with the fixes since last one?  (So conda pkg can use them).  Thanks! @Lykos153

**Comment by Lykos153** [comment]
I was planning to make the next release v1.0 and as I completely re-implemented large parts of the software, I wanted to do some thorough testing first. But maybe it's ready now for release. I had a few more features for v1.0 in mind, but I guess I just move them to v1.1

**Comment by Lykos153** [comment]
Done :)
