### ISSUE TITLE
setup silently fails in version 1.0.1

### ISSUE THREAD

**Issue by froseph** [Lykos153/git-annex-remote-googledrive#44]
After cloning a repository, I tried to set up my google drive special remote. It opened up the browser for me the authorize the application. When completing authorization I'm redirected to localhost with a plaintext success message. Coming back to the command prompt to enable the remote, `git-annex-remote-googldrive` is unable to find the credentials. See output below. Downgrading to version 0.11.4 allows me to setup and enable the remote.

```
~/annex-dir % git-annex-remote-googledrive setup
======
IMPORTANT: Google has started to lockdown their Google Drive API. This might affect access to your remotes.
Until this is settled you'll see a warning about this application not being verified by Google which you need to accept in order to proceed.
Read more on https://github.com/Lykos153/git-annex-remote-googledrive#google-drive-api-lockdown
======
Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=XXXXXXXXXXXX
Setup complete. An auth token was stored in .git/annex/othertmp. Now run 'git annex initremote' with your desired parameters. If you don't run it from the same folder, specify via token=path/to/token.json

~/annex-dir % git annex enableremote google
enableremote google
git-annex: No Credentials found. Run 'git-annex-remote-googledrive setup' in order to authenticate.
failed
git-annex: enableremote: 1 failed
```

**Comment by Lykos153** [comment]
Thanks for your report! Unfortunately I cannot reproduce this. Can you please check if after `git-annex-remote-googledrive setup` there is actually a token file in `.git/annex/othertmp`?
Also, please run `git annex enableremote google --debug` and post the output here. **But make sure to replace the lines `SETCONFIG root_id ...` and `SETCREDS credentials ...` if present!**

**Comment by froseph** [comment]
I tried to reproduce with a fresh clone and the latest version and it appeared to work fine this time. Closing out.
