### ISSUE TITLE
Are the Drive credentials encrypted?

### ISSUE THREAD

**Issue by vojta001** [Lykos153/git-annex-remote-googledrive#48]
According to [https://git-annex.branchable.com/encryption/](https://git-annex.branchable.com/encryption/)
> Special remotes that need some form of credentials, such as a password, may support embedding the credentials in the git repository, using embedcreds=yes. See individual special remotes' documentation for details. When credentials are embedded in the repository, they're also encrypted using whatever encryption setting has been selected for the repository.

however, I cannot see `embedcreds` option in yours docs (while claiming the Drive credentials are stored in the repo).

What is the reality? If I use this remote with `pubkey` encryption, will the Drive credentials be GPG encrypted as well? If so, I think it is worth mentioning it in the README, if not, it might be worth implementing.

**Comment by Lykos153** [comment]
Thanks for raising this issue! From what I understand this should be completely handled by git-annex. But apparently that does not happen. I raised an issue (here)[https://git-annex.branchable.com/bugs/embedcreds_with_external_special_remotes/]. So let's see.

**Comment by vojta001** [comment]
Thank you! I have read the comments to your bugreport and I am confused even more. What is the current state if I do not use `embedcreds=yes`? Will the credentials be stored in the repo unecrypted, or not stored at all?

**Comment by Lykos153** [comment]
git-annex-remote-googledrive uses the GET/SETCREDS requests of the [external special remote protocol](https://git-annex.branchable.com/design/external_special_remote_protocol/) to let git-annex handle the credentials. As documented on the linked page, if embedcreds=yes is specified, the credentials are stored within the git-annex branch of the repository, encrypted with the same method as the keys (none, hybrid, shared, pubkey, sharedpubkey). If embedcreds is not set to yes, the behaviour depends on the encryption. In case of hybrid, pubkey or sharedpubkey, the credentials are embedded in the repository as if embedcreds were set. For all other encryption methods (none and shared) the credentials are stored in a file within the .git directory unencrypted. I'm going to add this explanation to the readme. Thanks for asking! However, the current bug causes the credentials to never be embedded and instead always stored inside the git dir.

**Comment by Lykos153** [comment]
git-annex-remote-googledrive uses the GET/SETCREDS requests of the [external special remote protocol](https://git-annex.branchable.com/design/external_special_remote_protocol/) to let git-annex handle the credentials. As documented on the linked page, if embedcreds=yes is specified, the credentials are stored within the git-annex branch of the repository, encrypted with the same method as the keys (none, hybrid, shared, pubkey, sharedpubkey). If embedcreds is not set to yes, the behaviour depends on the encryption. In case of hybrid, pubkey or sharedpubkey, the credentials are embedded in the repository as if embedcreds were set. For all other encryption methods (none and shared) the credentials are stored in a file within the .git directory unencrypted.

I'm going to add this explanation to the readme. Thanks for asking!

However, the current bug causes the credentials to never be embedded and instead always stored inside the git dir.

**Comment by joeyh** [comment]
I've fixed the git-annex bug. Planning a release tomorrow due to this bug fix.

**Comment by Lykos153** [comment]
Thanks Joey!
