### ISSUE TITLE
Could not read token file: <path>

### ISSUE THREAD

**Issue by Fuco1** [Lykos153/git-annex-remote-googledrive#55]
I have multiple checkouts of the repository on different paths.  It seems this client stores the token path in the repo itself which then creates conflicts between different checkouts.

When  I run `enableremote` on a new computer it will give me 

```
[2020-08-30 20:42:29.579164] git-annex-remote-googledrive[1] --> GETCONFIG token
[2020-08-30 20:42:29.579418] git-annex-remote-googledrive[1] <-- VALUE /media/data-750/data/token.json
```

but this path does not exist here, the repo is under `/home/<user>/data` instead and the `setup` command gave me

```
Setup complete. An auth token was stored in /home/<user>/data/.git/annex/othertmp/git-annex-remote-googledrive.token. Now run 'git annex initremote' with your desired parameters.
```

Note that I'm trying to migrate from `gcloud` using instructions from readme.

How can I configure this to be per-checkout and not a globally shared value.

**Comment by Lykos153** [comment]
The option `token` is not intended to be stored permanently at all. However, due to a bug, it was't reset in case of errors (i.e. file not found).

**Comment by Fuco1** [comment]
I tried to upgrade with `pip3 install --upgrade` but it downloaded 1.2.0 version.

**Comment by Lykos153** [comment]
Sorry, forgot to update PyPI. Upgrading via pip should work now!

**Comment by Fuco1** [comment]
Yes, can confirm it upgrades now.  Thanks!  The token problem also seems to be fixed for me.
